#!/usr/bin/env python3
"""
Environment setup helper script
"""

import os
import sys
from pathlib import Path

def setup_environment():
    """Setup environment variables interactively"""
    
    print("🔧 Voice Agent System - Environment Setup")
    print("=" * 45)
    
    env_vars = {
        "OPENAI_API_KEY": "OpenAI API key (for GPT-4)",
        "DEEPGRAM_API_KEY": "Deepgram API key (for speech-to-text)",
        "ELEVENLABS_API_KEY": "ElevenLabs API key (for text-to-speech)"
    }
    
    env_file_path = Path(".env")
    
    print("This script will help you set up your API keys.")
    print("You can get these keys from:")
    print("  • OpenAI: https://platform.openai.com/api-keys")
    print("  • Deepgram: https://console.deepgram.com/")
    print("  • ElevenLabs: https://elevenlabs.io/")
    print()
    
    env_lines = []
    
    for var_name, description in env_vars.items():
        current_value = os.getenv(var_name)
        
        if current_value:
            print(f"✅ {var_name} is already set")
            env_lines.append(f"{var_name}={current_value}")
        else:
            print(f"\n🔑 {description}")
            
            while True:
                value = input(f"Enter {var_name} (or 'skip' to skip): ").strip()
                
                if value.lower() == 'skip':
                    print(f"⏭️  Skipped {var_name}")
                    break
                elif value:
                    env_lines.append(f"{var_name}={value}")
                    print(f"✅ {var_name} set")
                    break
                else:
                    print("❌ Please enter a valid API key or 'skip'")
    
    # Save to .env file
    if env_lines:
        with open(env_file_path, 'w') as f:
            f.write("# Voice Agent System API Keys\n")
            f.write("# Generated by setup_environment.py\n\n")
            for line in env_lines:
                f.write(line + "\n")
        
        print(f"\n💾 Environment variables saved to {env_file_path}")
    
    print("\n🎯 Next Steps:")
    print("  1. Run: python scripts/check_apis.py (to verify connectivity)")
    print("  2. Run: python src/demo_system.py (for demo without APIs)")
    print("  3. Run: python src/main_system.py (for full system with APIs)")

if __name__ == "__main__":
    setup_environment()